import streamlit as st

AZUREOPENAI_ENDPOINT = st.secrets["AZUREOPENAI_ENDPOINT"]
AZUREOPENAI_APIKEY = st.secrets["AZUREOPENAI_APIKEY"]
AZUREOPENAI_API_VERION = "2024-02-01"
AZUREOPENAI_MODEL = "gpt-4.1"

AZUREFOUNDRY_ENDPOINT = st.secrets["AZUREFOUNDRY_ENDPOINT"]
AZUREFOUNDRY_APIKEY = st.secrets["AZUREFOUNDRY_APIKEY"]
DEEPSEEK_DEPLOYMENT_NAME = "DeepSeek-V3.2-Speciale-1"
GPT5_4_DEPLOYMENT_NAME = "gpt-5.4-1"

SCREENSHOTMACHINE_API_KEY_LIST = st.secrets["SCREENSHOTMACHINE_API_KEY_LIST"]
