import streamlit as st

AZUREOPENAI_ENDPOINT = st.secrets["AZUREOPENAI_ENDPOINT"]
AZUREOPENAI_API_KEY = st.secrets["AZUREOPENAI_API_KEY"]
AZUREOPENAI_API_VERION = "2024-02-01"
AZUREOPENAI_MODEL = "gpt-4.1"

SCREENSHOTMACHINE_API_KEY_LIST = st.secrets["SCREENSHOTMACHINE_API_KEY_LIST"]

FIRECRAWL_API_KEY = st.secrets.get("FIRECRAWL_API_KEY")